// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateProductReader is a Reader for the CreateProduct structure.
type CreateProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewCreateProductAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateProductAccepted creates a CreateProductAccepted with default headers values
func NewCreateProductAccepted() *CreateProductAccepted {
	return &CreateProductAccepted{}
}

/* CreateProductAccepted describes a response with status code 202, with default header values.

CreateProductAccepted create product accepted
*/
type CreateProductAccepted struct {
}

func (o *CreateProductAccepted) Error() string {
	return fmt.Sprintf("[POST /products][%d] createProductAccepted ", 202)
}

func (o *CreateProductAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
