// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateProductReader is a Reader for the UpdateProduct structure.
type UpdateProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewUpdateProductAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateProductAccepted creates a UpdateProductAccepted with default headers values
func NewUpdateProductAccepted() *UpdateProductAccepted {
	return &UpdateProductAccepted{}
}

/* UpdateProductAccepted describes a response with status code 202, with default header values.

UpdateProductAccepted update product accepted
*/
type UpdateProductAccepted struct {
}

func (o *UpdateProductAccepted) Error() string {
	return fmt.Sprintf("[PUT /products/{id}][%d] updateProductAccepted ", 202)
}

func (o *UpdateProductAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
