consumes:
- application/json
definitions:
  Product:
    properties:
      createdAt:
        type: string
        x-go-name: CreatedAt
      description:
        type: string
        x-go-name: Description
      id:
        description: the id of the product
        format: int64
        minimum: 1
        type: integer
        x-go-name: ID
      name:
        type: string
        x-go-name: Name
      price:
        description: product price in cents
        format: int64
        minimum: 0
        type: integer
        x-go-name: Price
      sku:
        type: string
        x-go-name: SKU
      updatedAt:
        type: string
        x-go-name: UpdatedAt
    required:
    - id
    - price
    type: object
    x-go-package: github.com/chrischenyc/microservices-in-go/ep-07/data
info:
  description: Package classification of Product API
  version: 1.0.0
paths:
  /products:
    get:
      description: Returns a list of products
      operationId: list
      responses:
        "200":
          $ref: '#/responses/productsResponse'
      tags:
      - products
    post:
      description: Create a product
      operationId: create
      responses:
        "202":
          $ref: '#/responses/noContent'
      tags:
      - products
  /products/{id}:
    delete:
      description: Delete a product by its id
      operationId: delete
      parameters:
      - description: The id of the product
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "202":
          $ref: '#/responses/noContent'
      tags:
      - products
    put:
      description: Update a product by its id
      operationId: update
      parameters:
      - description: The id of the product
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "202":
          $ref: '#/responses/noContent'
      tags:
      - products
produces:
- application/json
responses:
  productsResponse:
    description: ""
    schema:
      items:
        $ref: '#/definitions/Product'
      type: array
schemes:
- http
swagger: "2.0"
